version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - "abby-chou.website.pipeline"
  discard-paths: no
  base-directory: build
