version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - "C:\Users\88697\Desktop\myproject\myresume"
  discard-paths: no
  base-directory: build
